### ISSUE TITLE
Shift + Esc not closing ConEmu tool window

### ISSUE THREAD

**Issue by nmklotas** [Therena/ConEmuIntegration#9] opened 2017-08-03 21:07 UTC
Hi,

It's common for Visual Studio to close tool windows with Shift + Esc shortcut.
But this does not work for ConEmu tool window.

It would be nice to have this functionality, because it's very convenient to bind keyboard shortcut to open tool window and close it with Shift + Esc.

Thanks

**Comment by Therena** [comment] 2017-08-16 20:11
Hi nmklotas,

thanks for sending in this issue.
Unfortunately this is not fixable for me. 

The problem is that the ConEmu Control is eating up all the keyboard shortcuts.
You can see this if you e.g. select the Visual Studio tab the Shift+Esc is working, but not if the focus is in the ConEmu control. 

I could try to contact the conemu team to implement a possibility to get the shortcuts forwarded to the parent application, but I cannot promise the success. 

Because this is not a bug in the extension, I will close the issue here.
Thanks for understanding.

**Closed as completed by Therena** 2017-08-16 20:11 UTC
Labels: invalid

**Comment by bobted** [comment] 2019-01-22 13:19
I think the keyboard shortcuts is a big deal. I just installed this and have the window docked and set to auto-hide. I'm able to use Ctrl+Tab to get to the window, but once ConEmu has focus, it won't let you Ctrl+Tab back to other tabs in VS. This means that I need to reach over to the mouse in order to set focus on code after using the console.

If that is what I have to do, then I am going to uninstall the extension and use an external console window as I've been doing for a while now. Integration into the VS IDE should be flawless and smooth as if the window is native to VS - otherwise is it too much noise and effort.
